# Generated by Django 4.0.3 on 2022-04-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_booking_booking_id_alter_guest_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='email',
        ),
        migrations.AddField(
            model_name='guest',
            name='gender',
            field=models.CharField(default='Male', max_length=6),
            preserve_default=False,
        ),
    ]
