# Generated by Django 4.0.3 on 2022-04-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0003_remove_guest_email_guest_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=7),
            preserve_default=False,
        ),
    ]
